#!/usr/bin/env bash

clone_settings() {
    cp "$PWD/bag/vscode/settings.json" $1
}

configure_vscode_insiders(){
    clone_settings "$HOME/Library/Application\ Support/Code\ -\ Insiders/User/"
    cp "$cwd/bag/vscode/keybindings-mac.json" "$HOME/Library/Application Support/Code - Insiders/User/keybindings.json"

    print_in_green "${indent} Code Insiders configured."
}

configure_vscode(){
    clone_settings "$HOME/Library/Application\ Support/Code/User/"
    cp "$PWD/bag/vscode/keybindings-mac.json" "$HOME/Library/Application\ Support/Code/User/keybindings.json"

    print_in_green "${indent} Code configured."
}
